--------------------------------------------------------
--  DDL for Table ARZ_RELATION
--------------------------------------------------------
{
  "name":"ARZ_RELATION",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table ARZ_PRD_DATA
--------------------------------------------------------
{
  "name":"ARZ_PRD_DATA",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ1_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ2_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table BACK_TEST_ERROR
--------------------------------------------------------
{
  "name":"BACK_TEST_ERROR",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GL_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SUM_TYPE2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_BR_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_TYPE_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOAN_BR_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOAN_TYPE_ERROR",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table BACK_TEST_DATA
--------------------------------------------------------
{
  "name":"BACK_TEST_DATA",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INTERVAL",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table NN_ERROR_FUNC_DETAILS
--------------------------------------------------------
{
  "name":"NN_ERROR_FUNC_DETAILS",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"DESCRIPTION",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table NN_ACTV_FUNC_DETAILS
--------------------------------------------------------
{
  "name":"NN_ACTV_FUNC_DETAILS",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"DESCRIPTION",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table HOMOGENEOUS_DEPOSIT_ACCOUNTING
--------------------------------------------------------
{
  "name":"HOMOGENEOUS_DEPOSIT_ACCOUNTING",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CATEGORY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CATEGORY_NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPOSIT_ACCOUNTING",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VALUE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFFDATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table HOMOGENEOUS_DEPOSIT
--------------------------------------------------------
{
  "name":"HOMOGENEOUS_DEPOSIT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CATEGORY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INPUT_BALANCE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OUTPU_BALANCE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PERCENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CATEGORY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CITY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CITY_NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STA_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"STA_NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table DAFTAR_KOL_SHOBE
--------------------------------------------------------
{
  "name":"DAFTAR_KOL_SHOBE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"FATHER_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table DAFTAR_KOL
--------------------------------------------------------
{
  "name":"DAFTAR_KOL",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"FATHER_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CODE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table REPORTS_DATA
--------------------------------------------------------
{
  "name":"REPORTS_DATA",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INTERVAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAX_LEVEL1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------
{
  "name":"REPORTS",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CUR_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TIMING_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"DES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TUNEL_IS_ENABLE",
      "dataDefault":"1 "
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPOSIT_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"CREATED",
      "dataDefault":"sysdate"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MASTER_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":60,
      "dataType":"NVARCHAR2",
      "name":"CREATEDBY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SCHEDULE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":60,
      "dataType":"NVARCHAR2",
      "name":"REPORTER_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATUS",
      "dataDefault":"NULL"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARCHIVED",
      "dataDefault":"0"
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"UPDATED",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"VALID_DATA_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TREE_VERSION_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LEDGER_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SYSTEM_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_BR_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_TYPE_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOAN_BR_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOAN_TYPE_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GL_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPB_BR_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPB_TYPE_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOANB_BR_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOANB_TYPE_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GLB_ERR",
      "dataDefault":"-1"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ORIGINAL_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GL_BR_ERR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GLB_BR_ERR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ZDBAR_RSB_ERR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ZDBAR_RSB_BKT_ERR",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table NN_PARAM
--------------------------------------------------------
{
  "name":"NN_PARAM",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ERROR_FUNC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ACTV_FUNC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"HIDDEN_SIZE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VALID_CHECK_NUM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LAG",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PRD_DAYS",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TRAIN_WINDOW",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VALIDATION",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BACKTEST_NUM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ACTIVE",
      "dataDefault":"0"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LAST_DATE",
      "dataDefault":"0"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SMOOTH_DEG",
      "dataDefault":"3"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SMOOTH_FRAME",
      "dataDefault":"11"
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TASHILAT_TYPE_MANDE
--------------------------------------------------------
{
  "name":"TASHILAT_TYPE_MANDE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table REPORTS_ERROR
--------------------------------------------------------
{
  "name":"REPORTS_ERROR",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_BR_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_TYPE_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOAN_BR_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LOAN_TYPE_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GL_ERROR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SUM_TYPE2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TASHILAT_SHOBE_MANDE
--------------------------------------------------------
{
  "name":"TASHILAT_SHOBE_MANDE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table SEPORDE_TYPE_MANDE
--------------------------------------------------------
{
  "name":"SEPORDE_TYPE_MANDE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table SEPORDE_SHOBE_MANDE
--------------------------------------------------------
{
  "name":"SEPORDE_SHOBE_MANDE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table REPORTS_SETTING
--------------------------------------------------------
{
  "name":"REPORTS_SETTING",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"REPORT_NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARCHIVE_PERIOD",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARCHIVE_PERIOD_MAX",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARCHIVE_NUM_MAX",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_TYPE_HOMEGENEOUS
--------------------------------------------------------
{
  "name":"TBL_TYPE_HOMEGENEOUS",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":2000,
      "dataType":"VARCHAR2",
      "name":"HOMEGENEOUS",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_TEST
--------------------------------------------------------
{
  "name":"TBL_TEST",
  "column":[
    {
      "nullable":"Y",
      "dataLength":4000,
      "dataType":"CLOB",
      "name":"VAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":4000,
      "dataType":"VARCHAR2",
      "name":"VAR_TEMP",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATES1",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_TEMP
--------------------------------------------------------
{
  "name":"TBL_TEMP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REP_REQ
--------------------------------------------------------
{
  "name":"TBL_REP_REQ",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BACK_TEST",
      "dataDefault":"0"
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"REF_USER_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CATEGORY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"REQ_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATUS",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"H_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ORIGINAL_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IS_ACTIVE_TUNEL",
      "dataDefault":"1 "
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IS_FINISH",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LEDGER_BRANCH
--------------------------------------------------------
{
  "name":"TBL_LEDGER_BRANCH",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CONCAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":1000,
      "dataType":"VARCHAR2",
      "name":"BAZE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NODE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LEDGER
--------------------------------------------------------
{
  "name":"TBL_LEDGER",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LEDGER_CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"NVARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT_CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NODE_TYPE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LAST_DAY_ARZ_RATE
--------------------------------------------------------
{
  "name":"TBL_LAST_DAY_ARZ_RATE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID_TIMING_DETAIL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LAST_DAY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_DEPOSIT_HOMOGENEOUS
--------------------------------------------------------
{
  "name":"TBL_DEPOSIT_HOMOGENEOUS",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CURRENCY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFFDATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CATEGORI_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"CATEGORY_NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_DEPOSIT
--------------------------------------------------------
{
  "name":"TBL_DEPOSIT",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEP_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_DEPOSIT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_BRANCH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"REF_CUSTOMER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DUE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BALANCE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"OPENING_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MODALITY_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_DEPOSIT_ACCOUNTING",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_CURRENCY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFFDATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_BACK_TEST_ARCHIVE
--------------------------------------------------------
{
  "name":"TBL_BACK_TEST_ARCHIVE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MIN_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAX_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_ARZ_RELATION
--------------------------------------------------------
{
  "name":"TBL_ARZ_RELATION",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_VALUE_TEMP_BACK_TEST
--------------------------------------------------------
{
  "name":"TBL_VALUE_TEMP_BACK_TEST",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INTERVAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CITY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_VALUE
--------------------------------------------------------
{
  "name":"TBL_VALUE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CITY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INTERVAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_TIMING",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_VALUE_TEMP_GAP
--------------------------------------------------------
{
  "name":"TBL_VALUE_TEMP_GAP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CITY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATE_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_VALUE_GAP
--------------------------------------------------------
{
  "name":"TBL_VALUE_GAP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_TIMING",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CITY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATE_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_DASHBOARD_DAILY_REPORT
--------------------------------------------------------
{
  "name":"TBL_DASHBOARD_DAILY_REPORT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFFDATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OUT_FLOW",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IN_FLOW",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PROFILE_MODEL_SETTING
--------------------------------------------------------
{
  "name":"TBL_PROFILE_MODEL_SETTING",
  "column":[
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"CREATE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ITEM_CNT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_CNT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IS_EMPTY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"H_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VERSION",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"DES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IS_ACTIVE",
      "dataDefault":"0 "
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"REF_USER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATUS",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"UPDATE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"REF_USER_UPDATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_NN_PARAM_NAMES
--------------------------------------------------------
{
  "name":"TBL_NN_PARAM_NAMES",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"MAX",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"FA_NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"EN_NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"DES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"MIN",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PROFIL_MODEL_SETING_DETAIL
--------------------------------------------------------
{
  "name":"TBL_PROFIL_MODEL_SETING_DETAIL",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_PROFILE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VALUE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"DES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"EN_NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"FA_NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_VALUE_TEMP
--------------------------------------------------------
{
  "name":"TBL_VALUE_TEMP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CITY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INTERVAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_GAP
--------------------------------------------------------
{
  "name":"TBL_GAP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IS_SINGLE_BRANCH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REQ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"BRANCH_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_TIMING_DETAIL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table DAFTAR_KOL_TJR
--------------------------------------------------------
{
  "name":"DAFTAR_KOL_TJR",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"FATHER_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table DAFTAR_KOL_SHOBE_TJR
--------------------------------------------------------
{
  "name":"DAFTAR_KOL_SHOBE_TJR",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":500,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"FATHER_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table REPORTS_DATA_TEMP
--------------------------------------------------------
{
  "name":"REPORTS_DATA_TEMP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOBE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DEPTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARENT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAX_LEVEL1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"INTERVAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_ID",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NODE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZ_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SEPORDE_MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TASHILAT_MANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFF_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAHR_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_DASHBOARD_DAILY_REPORT_TE
--------------------------------------------------------
{
  "name":"TBL_DASHBOARD_DAILY_REPORT_TE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DATA_TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"GAP",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EFFDATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OUT_FLOW",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IN_FLOW",
      "dataDefault":null
    }
  ]
}
