--------------------------------------------------------
--  DDL for Table TBL_LOAN
--------------------------------------------------------
{
  "name":"TBL_LOAN",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TAFKIK_BAKHSH_KHOSUSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NERKH_SUD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NAHVE_BAZ_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_NAHVE_BAZ_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"MARJA_TASVIB_KONANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EMHAL_SHODE_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOMARE_EMHAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_ASL_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_KOL_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_SARRESID_GOZASHTE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_MASHKUKOLVOSUL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_MOAVVAGH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEDAD_AGHSAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DORE_AGHSAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"REF_VASIGHE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"VAZIAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":10,
      "dataType":"VARCHAR2",
      "name":"TARIKH_TASHKIL_SHAMSI",
      "dataDefault":"TO_CHAR(\"TARIKH_TASHKIL\",'yyyy/mm/dd','nls_calendar=''Persian''')"
    },
    {
      "nullable":"Y",
      "dataLength":10,
      "dataType":"VARCHAR2",
      "name":"TARIKH_TASVIE_SHAMSI",
      "dataDefault":"TO_CHAR(\"TARIKH_TASVIE\",'yyyy/mm/dd','nls_calendar=''Persian''')"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":10,
      "dataType":"VARCHAR2",
      "name":"TARIKH_SARREDID_SHAMSI",
      "dataDefault":"TO_CHAR(\"TARIKH_SARREDID\",'yyyy/mm/dd','nls_calendar=''Persian''')"
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NOE_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAM_NOE_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_MAHIAT_MOTEGHAZI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TASHKIL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_ETA",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TASVIE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SARREDID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_AVVALIN_GHEST_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_MOSAVVAB",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ARZ",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ELLAT_DARKHAST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ELLAT_DARKHAST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ESTEFADE_AZ_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ESTEFADE_AZ_TASHILAT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PAYMENT
--------------------------------------------------------
{
  "name":"TBL_PAYMENT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PARDAKHT_SHODE_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_DARYAFT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SARRESID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAJHE_ELTEZAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_KHALES_BEDEHI_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SUD_MOSTATER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_ASL",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOMARE_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_GHEST_DARYAFT_SHODE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_COLLATERAL
--------------------------------------------------------
{
  "name":"TBL_COLLATERAL",
  "column":[
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_GHEYR_FAAL_SHODAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SARRESID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZESH_ARZYABI_SHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAZIAT_FAAL_BUDAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ZARIB_ARZESH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ZARIB_NAGHDINEGI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_NOE_VASIGHE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NOE_VASIGHE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ARZESH_VASIGHE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ARZESH_TARHIN_SHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TARHIN",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MODAT_TARHIN",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_GUARANTEE
--------------------------------------------------------
{
  "name":"TBL_GUARANTEE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DARSAD_NAGHDI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_NAGHDI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_GHEYR_NAGHDI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_GH_NAGHDI_AZAD_SHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"MOZUE_GHARARDAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MODAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAZIAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ARZ",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ISIC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"MAZMUN_LAH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EMKAN_TAMDID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAHVE_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ZINAF",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SODUR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SARRESID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_ZABT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NOE_ZEMANAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAM_NOE_ZEMANAT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_CUSTOMER
--------------------------------------------------------
{
  "name":"TBL_CUSTOMER",
  "column":[
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SATH_TAHSILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SABT_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"CUS_ID",
      "dataDefault":"TO_CHAR(\"ID\")"
    },
    {
      "nullable":"Y",
      "dataLength":2000,
      "dataType":"VARCHAR2",
      "name":"ADDRESS",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAZIAT_TAAHOL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_MELLI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOMARE_SODUR_SHENASNAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"MAHAL_SODUR_SHENASNAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAHIAT_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"SHAHR_TAVVALOD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"JENSIAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TAVVALOD",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_BRANCH
--------------------------------------------------------
{
  "name":"TBL_BRANCH",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DARAJE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_EFTETAH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BRN_ID",
      "dataDefault":"TO_CHAR(\"ID\")"
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_OSTAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_OSTAN",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_COLLATERAL_SETTING
--------------------------------------------------------
{
  "name":"TBL_COLLATERAL_SETTING",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ZARIB_NAGHD_SHAVANDEGI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_SAZANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_IJAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"TOZIHAT",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_NOE_VASIGHE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_NAVIX
--------------------------------------------------------
{
  "name":"TBL_NAVIX",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"B",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"M",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"K",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RWA",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"R",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"LGD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"PD",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EAD",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PROFILE_MASTER
--------------------------------------------------------
{
  "name":"TBL_PROFILE_MASTER",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAZIAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"TOZIHAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"JADVAL_ASLI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAM_SAZANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SYSTEMI",
      "dataDefault":"0 "
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_IJAD",
      "dataDefault":"SYSDATE "
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REL_PROFILE_MASTER_PROFILE
--------------------------------------------------------
{
  "name":"TBL_REL_PROFILE_MASTER_PROFILE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REL_ABAR_NAMAYE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REL_NAMAYE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_TABLES_INFORMATION
--------------------------------------------------------
{
  "name":"TBL_TABLES_INFORMATION",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"JADVAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"SOTUN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_FARSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":2000,
      "dataType":"VARCHAR2",
      "name":"QUERY",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NOE_DADE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAZIAT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LOAN_CATEGORY
--------------------------------------------------------
{
  "name":"TBL_LOAN_CATEGORY",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CATEGORY_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"TYPE_NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TYPE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"CATEGORY_NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PD
--------------------------------------------------------
{
  "name":"TBL_PD",
  "column":[
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"REF_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PD",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_C_PD
--------------------------------------------------------
{
  "name":"TBL_C_PD",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"C_PD",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_DAILY_IRB
--------------------------------------------------------
{
  "name":"TBL_DAILY_IRB",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"DATE_REPORT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"AVGPD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"AVGHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RWA",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RANGE
--------------------------------------------------------
{
  "name":"TBL_RANGE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"START_RANGE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"END_RANGE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COUNT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EEAD",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RANGE_DETAIL
--------------------------------------------------------
{
  "name":"TBL_RANGE_DETAIL",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CUMULATIVE_PO",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"POISSON",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CUMULATIVE_PO",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"POISSON",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RANGE_RESULT
--------------------------------------------------------
{
  "name":"TBL_RANGE_RESULT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CVAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"UEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CVAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"UEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EC",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT_MANDE_RIAL_ARZ
--------------------------------------------------------
{
  "name":"TBL_REPORT_MANDE_RIAL_ARZ",
  "column":[
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BE_PRE_YEAR",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"PRE_YEAR\"=0 AND \"CURRENT_MONTH\"=0) THEN 0 WHEN (\"PRE_YEAR\"=0 AND \"CURRENT_MONTH\"<>0) THEN 100 ELSE ROUND((\"CURRENT_MONTH\"-\"PRE_YEAR\")/\"PRE_YEAR\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BE_PRE_MONTH",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"PRE_MONTH\"=0 AND \"CURRENT_MONTH\"=0) THEN 0 WHEN (\"PRE_MONTH\"=0 AND \"CURRENT_MONTH\"<>0) THEN 100 ELSE ROUND((\"CURRENT_MONTH\"-\"PRE_MONTH\")/\"PRE_MONTH\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BE_ESFAND",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"ESFAND\"=0 AND \"CURRENT_MONTH\"=0) THEN 0 WHEN (\"ESFAND\"=0 AND \"CURRENT_MONTH\"<>0) THEN 100 ELSE ROUND((\"CURRENT_MONTH\"-\"ESFAND\")/\"ESFAND\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"KOL_OR_GHAIRE_JARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PRE_MONTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PRE_YEAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ESFAND",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CURRENT_MONTH",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT_5_SHOBE
--------------------------------------------------------
{
  "name":"TBL_REPORT_5_SHOBE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"SHAKHES",
      "dataDefault":"TO_CHAR(CASE \"MAH_JARI\" WHEN 0 THEN 0 ELSE ROUND(\"MAH_JARI2\"/\"MAH_JARI\",5) END )"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"DARSAD2",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"MAH_GOZASHTE2\"=0 AND \"MAH_JARI2\"=0) THEN 0 WHEN (\"MAH_GOZASHTE2\"=0 AND \"MAH_JARI2\"<>0) THEN 100 ELSE ROUND((\"MAH_JARI2\"-\"MAH_GOZASHTE2\")/\"MAH_GOZASHTE2\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAH_GOZASHTE2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAH_JARI2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"DARSADE",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"MAH_GOZASHTE\"=0 AND \"MAH_JARI\"=0) THEN 0 WHEN (\"MAH_GOZASHTE\"=0 AND \"MAH_JARI\"<>0) THEN 100 ELSE ROUND((\"MAH_JARI\"-\"MAH_GOZASHTE\")/\"MAH_GOZASHTE\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAH_GOZASHTE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MAH_JARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TABLE_S1
--------------------------------------------------------
{
  "name":"TABLE_S1",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SAHM2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEDAD2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SAHM1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEDAD1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT_TAGHIR_NPL_SHOAB
--------------------------------------------------------
{
  "name":"TBL_REPORT_TAGHIR_NPL_SHOAB",
  "column":[
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAKHES1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAKHES2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"DARSAD",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"SHAKHES2\"=0 AND \"SHAKHES1\"=0) THEN 0 WHEN (\"SHAKHES2\"=0 AND \"SHAKHES1\"<>0) THEN 100 ELSE ROUND((\"SHAKHES1\"-\"SHAKHES2\")/\"SHAKHES2\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TABLE_REPORT8_BRANCH
--------------------------------------------------------
{
  "name":"TABLE_REPORT8_BRANCH",
  "column":[
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ASL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SARRESID_GOZASHTE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MOAVAGH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MASHKOOK",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SAYER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"KHESARAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TOTAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DARSAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT_MANDE_TASHILAT
--------------------------------------------------------
{
  "name":"TBL_REPORT_MANDE_TASHILAT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BE_PRE_MONTH",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"PRE_MONTH\"=0 AND \"CURRENT_MONTH\"=0) THEN 0 WHEN (\"PRE_MONTH\"=0 AND \"CURRENT_MONTH\"<>0) THEN 100 ELSE ROUND((\"CURRENT_MONTH\"-\"PRE_MONTH\")/\"PRE_MONTH\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"KOL_OR_GHAIRE_JARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CURRENT_MONTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PRE_MONTH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ESFAND",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PRE_YEAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BE_ESFAND",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"ESFAND\"=0 AND \"CURRENT_MONTH\"=0) THEN 0 WHEN (\"ESFAND\"=0 AND \"CURRENT_MONTH\"<>0) THEN 100 ELSE ROUND((\"CURRENT_MONTH\"-\"ESFAND\")/\"ESFAND\"*100,0) END )"
    },
    {
      "nullable":"Y",
      "dataLength":40,
      "dataType":"VARCHAR2",
      "name":"BE_PRE_YEAR",
      "dataDefault":"TO_CHAR(CASE  WHEN (\"PRE_YEAR\"=0 AND \"CURRENT_MONTH\"=0) THEN 0 WHEN (\"PRE_YEAR\"=0 AND \"CURRENT_MONTH\"<>0) THEN 100 ELSE ROUND((\"CURRENT_MONTH\"-\"PRE_YEAR\")/\"PRE_YEAR\"*100,0) END )"
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TABLE_REPORT_S5
--------------------------------------------------------
{
  "name":"TABLE_REPORT_S5",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHAKHES_RISK",
      "dataDefault":"ROUND(\"MABLAGH1\"/\"MABLAGH2\"*100,3)"
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"SAHM2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"SAHM1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"SANAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT4_SHAKHES_RISK
--------------------------------------------------------
{
  "name":"TBL_REPORT4_SHAKHES_RISK",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M5",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"SHAKHES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M1",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M7",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M6",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M3",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M4",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"M2",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT_SAHM_AZ_KOL
--------------------------------------------------------
{
  "name":"TBL_REPORT_SAHM_AZ_KOL",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"CODE_NOE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"DARSAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"VALUE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_ARZ
--------------------------------------------------------
{
  "name":"TBL_ARZ",
  "column":[
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"NAME_ARZ",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ARZ",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LOAN_PAST
--------------------------------------------------------
{
  "name":"TBL_LOAN_PAST",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_ASL_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_KOL_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_SARRESID_GOZASHTE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_MASHKUKOLVOSUL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_MOAVVAGH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEDAD_AGHSAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DORE_AGHSAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"REF_VASIGHE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"VAZIAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":10,
      "dataType":"VARCHAR2",
      "name":"TARIKH_TASHKIL_SHAMSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":10,
      "dataType":"VARCHAR2",
      "name":"TARIKH_TASVIE_SHAMSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":10,
      "dataType":"VARCHAR2",
      "name":"TARIKH_SARREDID_SHAMSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFFDATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOMARE_EMHAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EMHAL_SHODE_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"MARJA_TASVIB_KONANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_NAHVE_BAZ_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NAHVE_BAZ_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ESTEFADE_AZ_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TAFKIK_BAKHSH_KHOSUSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NERKH_SUD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ESTEFADE_AZ_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ELLAT_DARKHAST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ELLAT_DARKHAST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ARZ",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_MOSAVVAB",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_AVVALIN_GHEST_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SARREDID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TASVIE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_ETA",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TASHKIL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_MAHIAT_MOTEGHAZI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NOE_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAM_NOE_TASHILAT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_CHANGE_IN_TIME
--------------------------------------------------------
{
  "name":"TBL_CHANGE_IN_TIME",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SUM_EAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"AVG_RR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"MIN_RR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"MAX_RR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"AVG_PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"MIN_PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"MAX_PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"EDATE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SUM_RWA",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_OSTAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHAHR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TYPE_CODE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_CREDIT_MAP
--------------------------------------------------------
{
  "name":"TBL_CREDIT_MAP",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"NAM_OSTAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEDAD_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RWA",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"AVG_PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"AVG_RR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFFDATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_SHAHR
--------------------------------------------------------
{
  "name":"TBL_SHAHR",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"NVARCHAR2",
      "name":"NAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID_TEMP",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":400,
      "dataType":"NVARCHAR2",
      "name":"TOZIH",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_OSTAN
--------------------------------------------------------
{
  "name":"TBL_OSTAN",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID_TEMP",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"NVARCHAR2",
      "name":"NAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":400,
      "dataType":"NVARCHAR2",
      "name":"TOZIH",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_CRPLUS
--------------------------------------------------------
{
  "name":"TBL_CRPLUS",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"E",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"HR",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_CRPLUS_RESULT
--------------------------------------------------------
{
  "name":"TBL_CRPLUS_RESULT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VAR2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EXPECTEDLOST2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EC2",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"OSTAN_NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"EFFDATE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT_TOZIE
--------------------------------------------------------
{
  "name":"TBL_REPORT_TOZIE",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"RR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"PD",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RANGE_OSTAN
--------------------------------------------------------
{
  "name":"TBL_RANGE_OSTAN",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATEE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"END_RANGE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"START_RANGE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COUNT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"PD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RANGE_DETAIL_OSTAN
--------------------------------------------------------
{
  "name":"TBL_RANGE_DETAIL_OSTAN",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATEE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"POISSON",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CUMULATIVE_PO",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATEE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"POISSON",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CUMULATIVE_PO",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RANGE_RESULT_OSTAN
--------------------------------------------------------
{
  "name":"TBL_RANGE_RESULT_OSTAN",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATEE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"UEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CVAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"DATEE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EC",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"RANGE_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"UEAD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"CVAR",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"OSTAN_ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TTTTT
--------------------------------------------------------
{
  "name":"TTTTT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NUM",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LOAN_1
--------------------------------------------------------
{
  "name":"TBL_LOAN_1",
  "column":[
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"VAZIAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAM_NOE_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_SHOBE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_MAHIAT_MOTEGHAZI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TASHKIL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_ETA",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_TASVIE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_SARREDID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"TARIKH_AVVALIN_GHEST_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_BAKHSH_EGHTESADI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MABLAGH_MOSAVVAB",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"ARZ",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ELLAT_DARKHAST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ELLAT_DARKHAST",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_ESTEFADE_AZ_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_ESTEFADE_AZ_TASHILAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TAFKIK_BAKHSH_KHOSUSI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"NERKH_SUD",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NAHVE_BAZ_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAM_NAHVE_BAZ_PARDAKHT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"MARJA_TASVIB_KONANDE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EMHAL_SHODE_NASHODE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"SHOMARE_EMHAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_MOSHTARI",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_ASL_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_KOL_VAM",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_SARRESID_GOZASHTE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_MASHKUKOLVOSUL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"MANDE_MOAVVAGH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"TEDAD_AGHSAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"DORE_AGHSAT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"REF_VASIGHE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"COD_NOE_TASHILAT",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PROFILE
--------------------------------------------------------
{
  "name":"TBL_PROFILE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REPORT_CNT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ITEM_CNT",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"H_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VERSION",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"REF_USER_UPDATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"UPDATE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATUS",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"REF_USER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"CREATE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"DES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":50,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"IS_EMPTY",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_PROFILE_DETAIL
--------------------------------------------------------
{
  "name":"TBL_PROFILE_DETAIL",
  "column":[
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"SRC_COLUMN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_PROFILE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":4000,
      "dataType":"CLOB",
      "name":"CONDITION",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_CUSTOMER_SEARCH_ITEM
--------------------------------------------------------
{
  "name":"TBL_CUSTOMER_SEARCH_ITEM",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"VALUE",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"EXIST_PROFILE_DETAIL",
      "dataDefault":"1 "
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"CONDITION",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"COLUMN_TYPE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_RATE
--------------------------------------------------------
{
  "name":"TBL_RATE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"RATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"TYPE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_LOAN_TYPE
--------------------------------------------------------
{
  "name":"TBL_LOAN_TYPE",
  "column":[
    {
      "nullable":"Y",
      "dataLength":100,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_LOAN_TYPE",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TBL_REPORT
--------------------------------------------------------
{
  "name":"TBL_REPORT",
  "column":[
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"REF_USER_UPDATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"UPDATE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"VERSION",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"TYPE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"H_ID",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_CUSTOMER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_BRANCH",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_COLLATERAL",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_GUARANTEE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"REF_LOAN",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"STATUS",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"REF_USER",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":7,
      "dataType":"DATE",
      "name":"CREATE_DATE",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"DES",
      "dataDefault":null
    },
    {
      "nullable":"Y",
      "dataLength":200,
      "dataType":"VARCHAR2",
      "name":"NAME",
      "dataDefault":null
    },
    {
      "nullable":"N",
      "dataLength":22,
      "dataType":"NUMBER",
      "name":"ID",
      "dataDefault":null
    }
  ]
}
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------
{
  "name":"TEST",
  "column":[
    {
      "nullable":"Y",
      "dataLength":20,
      "dataType":"VARCHAR2",
      "name":"COLUMN1",
      "dataDefault":null
    }
  ]
}
