--------------------------------------------------------
--  DDL for Table PKG_TJR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "AKIN"."PKG_TJR" AS
 PROCEDURE PRC_TRANSFER_ACCOUNTING;

 PROCEDURE PRC_TRANSFER_DEPOSIT;

 PROCEDURE PRC_TRANSFER_LOAN;

 PROCEDURE PRC_TRANSFER_PAYMENT;

 PROCEDURE PRC_TRANSFER_DEPOSIT_PROFIT ( RUN_DATE DATE );

 PROCEDURE PRC_J_TRANSFER_DEPOSIT ( INPAR_DATE DATE );

 PROCEDURE PRC_J_TRANSFER_LOAN ( INPAR_DATE DATE );

 PROCEDURE PRC_J_TRANSFER_DEPOSIT_PROFIT (RUN_DATE  DATE);

 PROCEDURE PRC_J_TRANSFER_PAYMENT ( INPAR_DATE DATE );
 END PKG_TJR;
--------------------------------------------------------
--  DDL for Table PKG_TJR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "AKIN"."PKG_TJR" AS
 PROCEDURE PRC_TRANSFER_ACCOUNTING;

 PROCEDURE PRC_TRANSFER_DEPOSIT;

 PROCEDURE PRC_TRANSFER_LOAN;

 PROCEDURE PRC_TRANSFER_PAYMENT;

 PROCEDURE PRC_TRANSFER_DEPOSIT_PROFIT ( RUN_DATE DATE );

 PROCEDURE PRC_J_TRANSFER_DEPOSIT ( INPAR_DATE DATE );

 PROCEDURE PRC_J_TRANSFER_LOAN ( INPAR_DATE DATE );

 PROCEDURE PRC_J_TRANSFER_DEPOSIT_PROFIT (RUN_DATE  DATE);

 PROCEDURE PRC_J_TRANSFER_PAYMENT ( INPAR_DATE DATE );
 END PKG_TJR;
