---------------------------------------------------------------
ALTER TABLE MYM_TEST
RENAME COLUMN COL2 TO COL;

ALTER TABLE MYM_TEST
MODIFY (COL1 NUMBER );

ALTER TABLE MYM_TEST
MODIFY (COL1 VARCHAR2(200) );

ALTER TABLE MYM_TEST
MODIFY (COL1 VARCHAR2(200) DEFAULT 100 );
--is
ALTER TABLE MYM_TEST
MODIFY (COL1 VARCHAR2(200) DEFAULT 100 NOT NULL);
--is null
ALTER TABLE MYM_TEST
MODIFY (COL1 NULL);
--all
ALTER TABLE MYM_TEST
RENAME COLUMN COL TO COL2;

ALTER TABLE MYM_TEST
MODIFY (COL2 DATE DEFAULT NULL NOT NULL);
-----------------------------------------------------------------
ALTER TABLE MYM_TEST
DROP COLUMN COL2;
-----------------------------------------------------------------
ALTER TABLE MYM_TEST
ADD (COL3 VARCHAR2(20) DEFAULT ali );